### ISSUE TITLE
Autofocus on Search field when the SearchPage component is rendered

### ISSUE THREAD

**Issue by mykeels** [Noblemajesty/more-recipe#25]
https://github.com/Noblemajesty/more-recipe/blob/b000a3f513d3a7fb7c8a90419a18d47c09639467/client/js/components/SearchPage.jsx#L61

I think you should add a `focused` prop which accepts a `Boolean` to the `<Search />` component, so its value can be `true` when it's used in the `SearchPage` component.

**Comment by FredDominant** [comment]
Fixed. Thank you.
